/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DripRouteImport } from './routes/drip'
import { Route as TonesRouteImport } from './routes/tones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DripRoute = DripRouteImport.update({
  id: '/drip',
  path: '/drip',
  getParentRoute: () => rootRouteImport,
} as any)
const TonesRoute = TonesRouteImport.update({
  id: '/tones',
  path: '/tones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drip': typeof DripRoute
  '/tones': typeof TonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drip': typeof DripRoute
  '/tones': typeof TonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drip': typeof DripRoute
  '/tones': typeof TonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drip' | '/tones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drip' | '/tones'
  id: '__root__' | '/' | '/drip' | '/tones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DripRoute: typeof DripRoute
  TonesRoute: typeof TonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drip': {
      id: '/drip'
      path: '/drip'
      fullPath: '/drip'
      preLoaderRoute: typeof DripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tones': {
      id: '/tones'
      path: '/tones'
      fullPath: '/tones'
      preLoaderRoute: typeof TonesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DripRoute: DripRoute,
  TonesRoute: TonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
